### ISSUE TITLE
Just saying thanks 👍

### ISSUE THREAD

**Issue by oscarhermoso** [grmkris/drizzle-supa-audit-example#1]
Very cool repo, used this as a reference to get something working with [SvelteKit SSE](https://github.com/tncrazvan/sveltekit-sse) and it's awesome.

Thanks for sharing this repo!

<details><summary>PS</summary>
<p>

Not sure how important it is but you could call `listener.unlisten()` in the `onAbort` callback

https://github.com/grmkris/drizzle-pg-notify-audit-table/blob/c3c1f69ab5b85ef1aed8d75a4e0766d44d066f11/src/index.ts#L120-L123

</p>
</details>

**Comment by grmkris** [comment]
thank you
